# Generated by Django 6.0 on 2026-01-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0003_contact_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
