# Generated by Django 6.0 on 2026-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafter', '0005_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='art_gallery/'),
        ),
    ]
